dojo.provide("dojox.charting.themes.Happy");
dojo.require("dojox.charting.Theme");

(function(){
	//	notes: colors generated by moving in 30 degree increments around the hue circle,
	//		at 90% saturation, using a B value of 75 (HSB model).
	var dxc=dojox.charting;
	dxc.themes.Happy=new dxc.Theme({
		colors: [
			dojo.colorFromHex("#bf1313"), // 0
			dojo.colorFromHex("#69bf13"), // 90
			dojo.colorFromHex("#13bfbf"), // 180
			dojo.colorFromHex("#6913bf"), // 270
			dojo.colorFromHex("#bf6913"), // 30
			dojo.colorFromHex("#13bf13"), // 120
			dojo.colorFromHex("#1369bf"), // 210
			dojo.colorFromHex("#bf13bf"), // 300
			dojo.colorFromHex("#bfbf13"), // 60
			dojo.colorFromHex("#13bf69"), // 150
			dojo.colorFromHex("#1313bf"), // 240
			dojo.colorFromHex("#bf1369")  // 330
		]
	});
})();
