var categories = [
	{ tag: "Accordion", label: "Accordion"},
	{ tag: "Badge", label: "Badge"},
	{ tag: "Button", label: "Button"},
	{ tag: "Carousel", label: "Carousel"},
	{ tag: "ContentPane", label: "ContentPane"},
	{ tag: "FixedSplitter", label: "FixedSplitter"},
	{ tag: "FeedReader", label: "FeedReader"},
	{ tag: "FormControls", label: "FormControls"},
	{ tag: "GridLayout", label: "GridLayout"},
	{ tag: "Heading", label: "Heading"},
	{ tag: "Icon", label: "Icon"},
	{ tag: "IconContainer", label: "IconContainer"},
	{ tag: "IconMenu", label: "IconMenu"},
	{ tag: "List", label: "List"},
	{ tag: "Media", label: "Media"},
	{ tag: "Opener", label: "Opener"},
	{ tag: "ProgressIndicator", label: "ProgressIndicator"},
	{ tag: "RoundRect", label: "RoundRect"},
	{ tag: "ScreenSizeAware", label: "ScreenSizeAware"},
	{ tag: "ScrollablePane", label: "ScrollablePane"},
	{ tag: "ScrollableView", label: "ScrollableView"},
	{ tag: "SimpleDialog", label: "SimpleDialog"},
	{ tag: "SpinWheel", label: "SpinWheel"},
	{ tag: "SwapView", label: "SwapView"},
	{ tag: "Switch", label: "Switch"},
	{ tag: "TabBar", label: "TabBar"},
	{ tag: "ToolBarButton", label: "ToolBarButton"},
	{ tag: "TreeView", label: "TreeView"},
	{ tag: "bookmarkable", label: "bookmarkable"},
	{ tag: "domButton", label: "domButton"},
	{ tag: "dynamic", label: "dynamic"},
	{ tag: "misc", label: "misc"},
	{ tag: "no-dojo", label: "no-dojo"},
	{ tag: "transition", label: "transition"}
];
var tests = [
	{ url: "test_Badge.html", tags: "Badge" },
	{ url: "test_ComboBox.html", tags: "FormControls" },
	{ url: "test_ContentPane.html", tags: "ContentPane" },
	{ url: "test_EdgeToEdge.html", tags: "List" },
	{ url: "test_EdgeToEdgeList-editable-sv.html", tags: "List" },
	{ url: "test_EdgeToEdgeList-editable.html", tags: "List" },
	{ url: "test_FixedSplitter-H2-prog.html", tags: "FixedSplitter" },
	{ url: "test_FixedSplitter-H2.html", tags: "FixedSplitter" },
	{ url: "test_FixedSplitter-V2H2-ContentPane.html", tags: "FixedSplitter" },
	{ url: "test_FixedSplitter-V2H2-change.html", tags: "FixedSplitter" },
	{ url: "test_FixedSplitter-V2H2.html", tags: "FixedSplitter" },
	{ url: "test_FixedSplitter-V3-var0.html", tags: "FixedSplitter" },
	{ url: "test_FixedSplitter-V3-var1.html", tags: "FixedSplitter" },
	{ url: "test_FixedSplitter-V3-var2.html", tags: "FixedSplitter" },
	{ url: "test_FixedSplitter-V3.html", tags: "FixedSplitter" },
	{ url: "test_FixedSplitter-orientation.html", tags: "FixedSplitter" },
	{ url: "test_FormControls.html", tags: "FormControls" },
	{ url: "test_Heading.html", tags: "Heading" },
	{ url: "test_IconContainer-badge.html", tags: "IconContainer" },
	{ url: "test_IconContainer-connect.html", tags: "IconContainer" },
	{ url: "test_IconContainer-editable.html", tags: "IconContainer" },
	{ url: "test_IconContainer-highlight.html", tags: "IconContainer" },
	{ url: "test_IconContainer-multi.html", tags: "IconContainer" },
	{ url: "test_IconContainer-prog.html", tags: "IconContainer" },
	{ url: "test_IconContainer-pubsub.html", tags: "IconContainer" },
	{ url: "test_IconContainer-removeConfirmation.html", tags: "IconContainer" },
	{ url: "test_IconContainer-single-below.html", tags: "IconContainer" },
	{ url: "test_IconContainer-single.html", tags: "IconContainer" },
	{ url: "test_IconContainer-sprite.html", tags: "IconContainer" },
	{ url: "test_IconContainer-transition-below.html", tags: "IconContainer" },
	{ url: "test_IconContainer-transition-zoom.html", tags: "IconContainer" },
	{ url: "test_IconContainer.html", tags: "IconContainer" },
	{ url: "test_ListItem-layout.html", tags: "List" },
	{ url: "test_Opener-Calendar.html", tags: "Opener" },
	{ url: "test_Opener-ColorPalette.html", tags: "Opener" },
	{ url: "test_Opener-ColorPicker.html", tags: "Opener" },
	{ url: "test_Opener-DateSpinWheel.html", tags: "Opener" },
	{ url: "test_ProgressIndicator-color.html", tags: "ProgressIndicator" },
	{ url: "test_ProgressIndicator-heading.html", tags: "ProgressIndicator" },
	{ url: "test_ProgressIndicator-size.html", tags: "ProgressIndicator" },
	{ url: "test_ProgressIndicator.html", tags: "ProgressIndicator" },
	{ url: "test_RoundRect.html", tags: "RoundRect" },
	{ url: "test_RoundRectList-editable-sv.html", tags: "List" },
	{ url: "test_RoundRectList-editable.html", tags: "List" },
	{ url: "test_RoundRectList.html", tags: "List" },
	{ url: "test_SpinWheel-1slot.html", tags: "SpinWheel" },
	{ url: "test_SpinWheel-custom.html", tags: "SpinWheel" },
	{ url: "test_SpinWheel-icons.html", tags: "SpinWheel" },
	{ url: "test_SpinWheelDatePicker-sv.html", tags: "SpinWheel" },
	{ url: "test_SpinWheelDatePicker.html", tags: "SpinWheel" },
	{ url: "test_SpinWheelTimePicker.html", tags: "SpinWheel" },
	{ url: "test_Switch-setter.html", tags: "Switch" },
	{ url: "test_Switch.html", tags: "Switch" },
	{ url: "test_TabBar-badge.html", tags: "TabBar" },
	{ url: "test_TabBar-seg-grouped-scroll.html", tags: "TabBar" },
	{ url: "test_TabBar-seg-grouped.html", tags: "TabBar" },
	{ url: "test_TabBar-seg.html", tags: "TabBar" },
	{ url: "test_TabBar.html", tags: "TabBar" },
	{ url: "test_Tooltip.html", tags: "Opener" },
	{ url: "test_TreeView.html", tags: "TreeView" },

	{ url: "test_ajax-html-sync.html", tags: "misc" },
	{ url: "test_ajax-html.html", tags: "misc" },
	{ url: "test_ajax-json-sync.html", tags: "misc" },
	{ url: "test_ajax-json.html", tags: "misc" },
	{ url: "test_bk_force-ContantView.html", tags: "bookmarkable" },
	{ url: "test_theme-switch.html", tags: "misc" }
];
