({
	"clearFilterDialogTitle": "フィルターのクリア",
	"filterDefDialogTitle": "フィルター",
	"incompleteRuleTip": "このルールは未完成です。",
	"ruleTitleTemplate": "ルール ${0}",
	
	"conditionEqual": "次の値と等しい",
	"conditionNotEqual": "次の値と等しくない",
	"conditionLess": "次の値より小さい",
	"conditionLessEqual": "次の値以下",
	"conditionLarger": "次の値より大きい",
	"conditionLargerEqual": "次の値以上",
	"conditionContains": "次の値を含む",
	"conditionIs": "は",
	"conditionStartsWith": "次の値で始まる",
	"conditionEndWith": "次の値で終わる",
	"conditionNotContain": "次の値を含まない",
	"conditionIsNot": " が  ではありません",
	"conditionNotStartWith": "次の値で始まらない",
	"conditionNotEndWith": "次の値で終わらない",
	"conditionBefore": "次の値より前",
	"conditionAfter": "次の値より後",
	"conditionRange": "次の範囲",
	
	"all": "すべて",
	"any": "任意",
	"relationAll": "すべてのルール",
	"waiRelAll": "次のすべてのルールを突き合わせ:",
	"relationAny": "任意のルール",
	"waiRelAny": "次の任意のルールを突き合わせ:",
	"relationMsgFront": "次を突き合わせ",
	"relationMsgTail": "",
	"and": " および ",
	"or": "または",
	
	"addRuleButton": "ルールの追加",
	"waiAddRuleButton": "新規ルールの追加",
	"removeRuleButton": "ルールの削除",
	"waiRemoveRuleButtonTemplate": "ルール ${0} の削除",
	
	"cancelButton": "キャンセル",
	"waiCancelButton": "このダイアログのキャンセル",
	"clearButton": "クリア",
	"waiClearButton": "フィルターのクリア",
	"filterButton": "フィルター",
	"waiFilterButton": "フィルターの送信",
	
	"columnSelectLabel": "列",
	"waiColumnSelectTemplate": "ルール ${0} の列",
	"conditionSelectLabel": "条件",
	"waiConditionSelectTemplate": "ルール ${0} の条件",
	"valueBoxLabel": "値",
	"waiValueBoxTemplate": "ルール ${0} のフィルターの値を入力",
	
	"rangeTo": "比較基準",
	"rangeTemplate": "${0} から ${1} まで",
	
	"statusTipHeaderColumn": "列",
	"statusTipHeaderCondition": "ルール",
	"statusTipTitle": "フィルター・バー",
	"statusTipMsg": "${0} の値をフィルターに掛けるには、ここのフィルター・バーをクリックしてください。",
	"anycolumn": "任意の列",
	"statusTipTitleNoFilter": "フィルター・バー",
	"statusTipTitleHasFilter": "フィルター",
	"statusTipRelPre": "次を突き合わせ",
	"statusTipRelPost": "ルール。",
	
	"defaultItemsName": "項目",
	"filterBarMsgHasFilterTemplate": "${1} ${2} 中 ${0} が表示されています。",
	"filterBarMsgNoFilterTemplate": "フィルターが適用されていません",
	
	"filterBarDefButton": "フィルターの定義",
	"waiFilterBarDefButton": "表のフィルター",
	"a11yFilterBarDefButton": "フィルター...",
	"filterBarClearButton": "フィルターのクリア",
	"waiFilterBarClearButton": "フィルターのクリア",
	"closeFilterBarBtn": "フィルター・バーを閉じる",
	
	"clearFilterMsg": "これにより、フィルターが削除され、使用可能なすべてのレコードが表示されます。",
	"anyColumnOption": "任意の列",
	
	"trueLabelEditable": "チェックマークが付いている",
	"trueLabel": "True",
	"falseLabel": "False"
})

