({
	/* These are already handled in the default RTE
		amp:"ampersand",lt:"less-than sign",
		gt:"greater-than sign",
		nbsp:"no-break space <br> non-breaking space",
		quot:"quote",
	*/
	iexcl:"inverted exclamation mark",
	cent:"cent sign",
	pound:"pound sign",
	curren:"currency sign",
	yen:"yen sign <br> yuan sign",
	brvbar:"broken bar <br> broken vertical bar",
	sect:"section sign",
	uml:"diaeresis <br> spacing diaeresis",
	copy:"copyright sign",
	ordf:"feminine ordinal indicator",
	laquo:"left-pointing double angle quotation mark <br> left pointing guillemet",
	not:"not sign",
	shy:"soft hyphen <br> discretionary hyphen",
	reg:"registered sign <br> registered trade mark sign",
	macr:"macron <br> spacing macron <br> overline <br> APL overbar",
	deg:"degree sign",
	plusmn:"plus-minus sign <br> plus-or-minus sign",
	sup2:"superscript two <br> superscript digit two <br> squared",
	sup3:"superscript three <br> superscript digit three <br> cubed",
	acute:"acute accent <br> spacing acute",
	micro:"micro sign",
	para:"pilcrow sign <br> paragraph sign",
	middot:"middle dot <br> Georgian comma <br> Greek middle dot",
	cedil:"cedilla <br> spacing cedilla",
	sup1:"superscript one <br> superscript digit one",
	ordm:"masculine ordinal indicator",
	raquo:"right-pointing double angle quotation mark <br> right pointing guillemet",
	frac14:"vulgar fraction one quarter <br> fraction one quarter",
	frac12:"vulgar fraction one half <br> fraction one half",
	frac34:"vulgar fraction three quarters <br> fraction three quarters",
	iquest:"inverted question mark <br> turned question mark",
	Agrave:"Latin capital letter A with grave <br> Latin capital letter A grave",
	Aacute:"Latin capital letter A with acute",
	Acirc:"Latin capital letter A with circumflex",
	Atilde:"Latin capital letter A with tilde",
	Auml:"Latin capital letter A with diaeresis",
	Aring:"Latin capital letter A with ring above <br> Latin capital letter A ring",
	AElig:"Latin capital letter AE <br> Latin capital ligature AE",
	Ccedil:"Latin capital letter C with cedilla",
	Egrave:"Latin capital letter E with grave",
	Eacute:"Latin capital letter E with acute",
	Ecirc:"Latin capital letter E with circumflex",
	Euml:"Latin capital letter E with diaeresis",
	Igrave:"Latin capital letter I with grave",
	Iacute:"Latin capital letter I with acute",
	Icirc:"Latin capital letter I with circumflex",
	Iuml:"Latin capital letter I with diaeresis",
	ETH:"Latin capital letter ETH",
	Ntilde:"Latin capital letter N with tilde",
	Ograve:"Latin capital letter O with grave",
	Oacute:"Latin capital letter O with acute",
	Ocirc:"Latin capital letter O with circumflex",
	Otilde:"Latin capital letter O with tilde",
	Ouml:"Latin capital letter O with diaeresis",
	times:"multiplication sign",
	Oslash:"Latin capital letter O with stroke <br> Latin capital letter O slash",
	Ugrave:"Latin capital letter U with grave",
	Uacute:"Latin capital letter U with acute",
	Ucirc:"Latin capital letter U with circumflex",
	Uuml:"Latin capital letter U with diaeresis",
	Yacute:"Latin capital letter Y with acute",
	THORN:"Latin capital letter THORN",
	szlig:"Latin small letter sharp s <br> ess-zed",
	agrave:"Latin small letter a with grave <br> Latin small letter a grave",
	aacute:"Latin small letter a with acute",
	acirc:"Latin small letter a with circumflex",
	atilde:"Latin small letter a with tilde",
	auml:"Latin small letter a with diaeresis",
	aring:"Latin small letter a with ring above <br> Latin small letter a ring",
	aelig:"Latin small letter ae <br> Latin small ligature ae",
	ccedil:"Latin small letter c with cedilla",
	egrave:"Latin small letter e with grave",
	eacute:"Latin small letter e with acute",
	ecirc:"Latin small letter e with circumflex",
	euml:"Latin small letter e with diaeresis",
	igrave:"Latin small letter i with grave",
	iacute:"Latin small letter i with acute",
	icirc:"Latin small letter i with circumflex",
	iuml:"Latin small letter i with diaeresis",
	eth:"Latin small letter eth",
	ntilde:"Latin small letter n with tilde",
	ograve:"Latin small letter o with grave",
	oacute:"Latin small letter o with acute",
	ocirc:"Latin small letter o with circumflex",
	otilde:"Latin small letter o with tilde",
	ouml:"Latin small letter o with diaeresis",
	divide:"division sign",
	oslash:"Latin small letter o with stroke <br> Latin small letter o slash",
	ugrave:"Latin small letter u with grave",
	uacute:"Latin small letter u with acute",
	ucirc:"Latin small letter u with circumflex",
	uuml:"Latin small letter u with diaeresis",
	yacute:"Latin small letter y with acute",
	thorn:"Latin small letter thorn",
	yuml:"Latin small letter y with diaeresis",

// Greek Characters and Symbols
	fnof:"Latin small f with hook <br> function <br> florin",
	Alpha:"Greek capital letter alpha",
	Beta:"Greek capital letter beta",
	Gamma:"Greek capital letter gamma",
	Delta:"Greek capital letter delta",
	Epsilon:"Greek capital letter epsilon",
	Zeta:"Greek capital letter zeta",
	Eta:"Greek capital letter eta",
	Theta:"Greek capital letter theta",
	Iota:"Greek capital letter iota",
	Kappa:"Greek capital letter kappa",
	Lambda:"Greek capital letter lambda",
	Mu:"Greek capital letter mu",
	Nu:"Greek capital letter nu",
	Xi:"Greek capital letter xi",
	Omicron:"Greek capital letter omicron",
	Pi:"Greek capital letter pi",
	Rho:"Greek capital letter rho",
	Sigma:"Greek capital letter sigma",
	Tau:"Greek capital letter tau",
	Upsilon:"Greek capital letter upsilon",
	Phi:"Greek capital letter phi",
	Chi:"Greek capital letter chi",
	Psi:"Greek capital letter psi",
	Omega:"Greek capital letter omega",
	alpha:"Greek small letter alpha",
	beta:"Greek small letter beta",
	gamma:"Greek small letter gamma",
	delta:"Greek small letter delta",
	epsilon:"Greek small letter epsilon",
	zeta:"Greek small letter zeta",
	eta:"Greek small letter eta",
	theta:"Greek small letter theta",
	iota:"Greek small letter iota",
	kappa:"Greek small letter kappa",
	lambda:"Greek small letter lambda",
	mu:"Greek small letter mu",
	nu:"Greek small letter nu",
	xi:"Greek small letter xi",
	omicron:"Greek small letter omicron",
	pi:"Greek small letter pi",
	rho:"Greek small letter rho",
	sigmaf:"Greek small letter final sigma",
	sigma:"Greek small letter sigma",
	tau:"Greek small letter tau",
	upsilon:"Greek small letter upsilon",
	phi:"Greek small letter phi",
	chi:"Greek small letter chi",
	psi:"Greek small letter psi",
	omega:"Greek small letter omega",
	thetasym:"Greek small letter theta symbol",
	upsih:"Greek upsilon with hook symbol",
	piv:"Greek pi symbol",
	bull:"bullet <br> black small circle",
	hellip:"horizontal ellipsis <br> three dot leader",
	prime:"prime <br> minutes <br> feet",
	Prime:"double prime <br> seconds <br> inches",
	oline:"overline <br> spacing overscore",
	frasl:"fraction slash",
	weierp:"script capital P <br> power set <br> Weierstrass p",
	image:"blackletter capital I <br> imaginary part",
	real:"blackletter capital R <br> real part symbol",
	trade:"trade mark sign",
	alefsym:"alef symbol <br> first transfinite cardinal",
	larr:"leftwards arrow",
	uarr:"upwards arrow",
	rarr:"rightwards arrow",
	darr:"downwards arrow",
	harr:"left right arrow",
	crarr:"downwards arrow with corner leftwards <br> carriage return",
	lArr:"leftwards double arrow",
	uArr:"upwards double arrow",
	rArr:"rightwards double arrow",
	dArr:"downwards double arrow",
	hArr:"left right double arrow",
	forall:"for all",
	part:"partial differential",
	exist:"there exists",
	empty:"empty set <br> null set <br> diameter",
	nabla:"nabla <br> backward difference",
	isin:"element of",
	notin:"not an element of",
	ni:"contains as member",
	prod:"n-ary product <br> product sign",
	sum:"n-ary sumation",
	minus:"minus sign",
	lowast:"asterisk operator",
	radic:"square root <br> radical sign",
	prop:"proportional to",
	infin:"infinity",
	ang:"angle",
	and:"logical and <br> wedge",
	or:"logical or <br> vee",
	cap:"intersection <br> cap",
	cup:"union <br> cup","int":"integral",
	there4:"therefore",
	sim:"tilde operator <br> varies with <br> similar to",
	cong:"approximately equal to",
	asymp:"almost equal to <br> asymptotic to",
	ne:"not equal to",
	equiv:"identical to",
	le:"less-than or equal to",
	ge:"greater-than or equal to",
	sub:"subset of",
	sup:"superset of",
	nsub:"not a subset of",
	sube:"subset of or equal to",
	supe:"superset of or equal to",
	oplus:"circled plus <br> direct sum",
	otimes:"circled times <br> vector product",
	perp:"up tack <br> orthogonal to <br> perpendicular",
	sdot:"dot operator",
	lceil:"left ceiling <br> APL upstile",
	rceil:"right ceiling",
	lfloor:"left floor <br> APL downstile",
	rfloor:"right floor",
	lang:"left-pointing angle bracket <br> bra",
	rang:"right-pointing angle bracket <br> ket",
	loz:"lozenge",
	spades:"black spade suit",
	clubs:"black club suit <br> shamrock",
	hearts:"black heart suit <br> valentine",
	diams:"black diamond suit",
	OElig:"Latin capital ligature OE",
	oelig:"Latin small ligature oe",
	Scaron:"Latin capital letter S with caron",
	scaron:"Latin small letter s with caron",
	Yuml:"Latin capital letter Y with diaeresis",
	circ:"modifier letter circumflex accent",
	tilde:"small tilde",
	ensp:"en space",
	emsp:"em space",
	thinsp:"thin space",
	zwnj:"zero width non-joiner",
	zwj:"zero width joiner",
	lrm:"left-to-right mark",
	rlm:"right-to-left mark",
	ndash:"en dash",
	mdash:"em dash",
	lsquo:"left single quotation mark",
	rsquo:"right single quotation mark",
	sbquo:"single low-9 quotation mark",
	ldquo:"left double quotation mark",
	rdquo:"right double quotation mark",
	bdquo:"double low-9 quotation mark",
	dagger:"dagger",
	Dagger:"double dagger",
	permil:"per mille sign",
	lsaquo:"single left-pointing angle quotation mark",
	rsaquo:"single right-pointing angle quotation mark",
	euro:"euro sign"
})
