({
	"clearFilterDialogTitle": "清除过滤器",
	"filterDefDialogTitle": "过滤器",
	"incompleteRuleTip": "此规则不完整。",
	"ruleTitleTemplate": "规则 ${0}",
	
	"conditionEqual": "等于",
	"conditionNotEqual": "不等于",
	"conditionLess": "小于",
	"conditionLessEqual": "小于等于",
	"conditionLarger": "大于",
	"conditionLargerEqual": "大于等于",
	"conditionContains": "包含",
	"conditionIs": "是",
	"conditionStartsWith": "开始于",
	"conditionEndWith": "结束于",
	"conditionNotContain": "不包含",
	"conditionIsNot": "不是",
	"conditionNotStartWith": "不是开始于",
	"conditionNotEndWith": "不是结束于",
	"conditionBefore": "前",
	"conditionAfter": "后",
	"conditionRange": "范围",
	"conditionIsEmpty": "为空",
	
	"all": "所有",
	"any": "任意",
	"relationAll": "所有规则",
	"waiRelAll": "与以下所有规则匹配：",
	"relationAny": "任意规则",
	"waiRelAny": "与以下任意规则匹配：",
	"relationMsgFront": "匹配",
	"relationMsgTail": "",
	"and": "和",
	"or": "或",
	
	"addRuleButton": "添加规则",
	"waiAddRuleButton": "新增规则",
	"removeRuleButton": "除去规则",
	"waiRemoveRuleButtonTemplate": "除去规则 ${0}",
	
	"cancelButton": "取消",
	"waiCancelButton": "取消此对话",
	"clearButton": "清除",
	"waiClearButton": "清除过滤器",
	"filterButton": "过滤器",
	"waiFilterButton": "提交过滤器",
	
	"columnSelectLabel": "列",
	"waiColumnSelectTemplate": "${0} 规则列",
	"conditionSelectLabel": "条件",
	"waiConditionSelectTemplate": "${0} 规则条件",
	"valueBoxLabel": "值",
	"waiValueBoxTemplate": "为 ${0} 规则向过滤器输入值",
	
	"rangeTo": "到",
	"rangeTemplate": "从 ${0} 到 ${1}",
	
	"statusTipHeaderColumn": "列",
	"statusTipHeaderCondition": "规则",
	"statusTipTitle": "过滤器栏",
	"statusTipMsg": "在此处单击过滤器栏以根据 ${0} 中的值进行过滤。",
	"anycolumn": "任意列",
	"statusTipTitleNoFilter": "过滤器栏",
	"statusTipTitleHasFilter": "过滤器",
	"statusTipRelPre": "匹配",
	"statusTipRelPost": "规则。",
	
	"defaultItemsName": "项",
	"filterBarMsgHasFilterTemplate": "${0} of ${1} ${2} shown.",
	"filterBarMsgNoFilterTemplate": "未应用过滤器",
	
	"filterBarDefButton": "定义过滤器",
	"waiFilterBarDefButton": "过滤表",
	"a11yFilterBarDefButton": "过滤器...",
	"filterBarClearButton": "清除过滤器",
	"waiFilterBarClearButton": "清除过滤器",
	"closeFilterBarBtn": "关闭过滤器栏",
	
	"clearFilterMsg": "将除去过滤器并显示所有可用记录。",
	"anyColumnOption": "任意列",
	
	"trueLabelEditable": "已检查",
	"trueLabel": "True",
	"falseLabel": "False"
})

